# Test File get the full transcript text (from documentation)
from youtube_transcript_api import YouTubeTranscriptApi


ytt_api = YouTubeTranscriptApi()
video_id =   "GYt5093aCQM"  

# retrieve the available transcripts
transcript_list = ytt_api.list(video_id)
text=""
# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    # print(
    #     transcript.video_id,
    #     transcript.language,
    #     transcript.language_code,
    #     # whether it has been manually created or generated by YouTube
    #     transcript.is_generated,
    #     # whether this transcript can be translated or not
    #     transcript.is_translatable,
    #     # a list of languages the transcript can be translated to
    #     transcript.translation_languages,
    # )

    # fetch the actual transcript data
    # print(transcript.fetch())
    # Format of this is : FetchedTranscriptSnippet(text='అంటుండు.', s     start=201.76, duration=2.32) this is not array
    # From this lets just take the text part
      
    for item in transcript.fetch():
        text += item.text 

        # full_text = full_text.replace("'", "").replace('"', "")     # (removing quotes to avoid issues in prompts)

print(text)